### ISSUE TITLE
dcache namespace for BlockDownloadVerify agent misses dcache.pm file

### ISSUE THREAD

**Issue by andelpe** [dmwm/PHEDEX#1013]
After migrating to SL6 (cms+PHEDEX+4.1.7-1-1.x86_64), we have found out that the BlockDownloadVerify agent used with `-namespace dcache` complains with `alert: PHEDEX::Core::Loader: no module found for action "dcache"`. Looking at the RPM, I see that while the directory `perl_lib/PHEDEX/Namespace/dcache` exists, the file `perl_lib/PHEDEX/Namespace/dcache.pm` is missing. Others, such as `castor.pm` or `dpm.pm` do exist. 

Is this intentional and I need to change something in my BlockDownloadVerify agent configuration or is really a packaging problem? When I have just dropped the `dcache.pm` file (found in github) in the `Namespace` dir, the agent has started to work fine again.

Cheers,
   Antonio Delgado

**Comment by nikmagini** [comment]
Hi Antonio,

indeed it looks like a packaging error introduced with 4.1.4 - I committed a fix, it will be included with the next rpm build. In the meantime, copying the file manually to the directory works.

Thanks for reporting!
Cheers
Nicolo'

**Comment by nikmagini** [comment]
Hi Antonio,

fixed with new agent build 4.1.7-comp

Closing

Cheers,
Nicolo'
