### ISSUE TITLE
Warning during Watchdog agent startup

### ISSUE THREAD

**Issue by nikmagini** [dmwm/PHEDEX#1021]
With PHEDEX_4_1_7, the Watchdog agent prints out the following warning during startup if the --limit option is not set:

Use of uninitialized value $_ in split at /home/grid/phedex/sw/slc6_amd64_gcc481/cms/PHEDEX/4.1.7-comp/perl_lib/PHEDEX/Core/Config/Factory.pm line 146.

Setting to lowest priority since it's a harmless warning message.

**Comment by marianne013** [comment]
We see this from our restart cron job. It's not clear to me where (and to what) --limit should be set to work around this.

**Comment by nikmagini** [comment]
Hi Daniela,

the warning is harmless. Setting -limit is optional and the agent is working properly despite the warning message.
Anyway I have now committed a fix to suppress the warning, it will be in the next release.

P.S. You can find out the syntax of agent config options by invoking the agent help i.e.
PHEDEX/Utilities/AgentFactory.pl --help

**Comment by nikmagini** [comment]
Released in 4.2.0
