### ISSUE TITLE
4.2.0 FTS3 backend: don't put null values in the json copyjob

### ISSUE THREAD

**Issue by nikmagini** [dmwm/PHEDEX#1044]
The FTS3 REST CLI doesn't interpret properly null values in the json copy job, it treats them as string with "null" value instead. E.g.

{"Files":[{"filesize":"2684354560","sources":["srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/PhEDEx_Debug/LoadTest07Source/DE_KIT_Disk_1B"],"checksums":null,"metadata":null,"destinations":["gsiftp://eoscmsftp.cern.ch//eos/cms/tier0/store/PhEDEx_LoadTest07/LoadTest07_Debug_T1_DE_KIT_Disk/T0_CH_CERN_Disk/28/LoadTest07_DE_KIT_Disk_1B_P2eYi0j3zSoX6tJU_28"]}]}

This causes issues for example when submitting a job with "checksums":null - instead of skipping the checksum comparison for missing value, it triggers relaxed checksum comparison, resulting in a transfer error.

null values should be dropped from the copyjob before generating the json

**Comment by alberto-sanchez** [comment]
in #1045 I tried to address this.

**Comment by nikmagini** [comment]
Looks fixed in pre4. Thanks!
