### ISSUE TITLE
internal server error in phedex transfer approval

### ISSUE THREAD

**Issue by prebello** [dmwm/PHEDEX#1120]
Dear experts,
while trying to approve the Phedex transfer
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1623222
I have received many times the error msg
Apologies, looks like we have an internal server error, details of which below. If the problem persists, please submit a bug report.

Could you please check? Thank you

**Comment by nataliaratnikova** [comment]
For the record, I found an erro record  in web server backend log  vocms0161/phedex/error_log_20190210.txt:

2019-02-10 00:31:46 UTC: error: id=269cc77a4f92cc8155d59cc38cd9022a Died at /data/srv/state/phedex/htdocs/WebSite/access25 line 4362, <F> line 3.

Looks like a transient problem,  user was able to approve request 5min later.
