### ISSUE TITLE
UnroutableData module: Data which cannot be routed for some reason or other

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/PHEDEX#615]
Original Savannah ticket 63191 reported by wildish on Fri Feb 19 08:59:15 2010.

- List of subscribed data (node,block) which cannot be routed to the destination, due to lack of commissioned links or otherwise

- datasvc/blockreplicas vs. datasvc/routedblocks provides the data, need routedblocks to be released.

**Comment by nikmagini** [comment]
Hi,

closing because the different classes of 'stuck data' mentioned in https://github.com/dmwm/PHEDEX/issues/615#issuecomment-26934365 can now be monitored - since quite some time - through the 'blockarrive' datasvc API:

https://cmsweb.cern.ch/phedex/datasvc/doc/blockarrive#basis_values

Cheers
N
