### ISSUE TITLE
t_adm_link_param table can have rows with 0 latency when there are pending files

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/PHEDEX#772]
Original Savannah ticket 83051 reported by None on Wed Jun  8 15:02:36 2011.

I recently observed that the t_adm_link_param table can occasionally rows with xfer_latency=0 and pend_bytes=0 when there are in fact pending files in the transfer queue on the link.

This is reflected in the t_history_link_stats table, where the pend_bytes value is correctly !=0 but the corresponding calculated param_latency is = 0.

param_latency is supposed to be proportional to pend_bytes, so there must be an issue in the latency calculation in the PerfMonitor agent.

For example:

+verbatim+
SQL&gt; r
  1* select * from t_adm_link_param where from_node=1261 and to_node=9

 FROM_NODE    TO_NODE TIME_UPDATE  TIME_SPAN PEND_BYTES DONE_BYTES  TRY_BYTES  XFER_RATE XFER_LATENCY
---------- ---------- ----------- ---------- ---------- ---------- ---------- ---------- ------------
      1261          9  1307536800      17700          0 7.5442E+11 1.6284E+11 42622776.5            0

SQL&gt; select * from t_history_link_stats where from_node=1261 and to_node=9 and timebin=1307536800;

   TIMEBIN  TIMEWIDTH  FROM_NODE    TO_NODE   PRIORITY PEND_FILES PEND_BYTES WAIT_FILES WAIT_BYTES COOL_FILES COOL_BYTES READY_FILES READY_BYTES XFER_FILES XFER_BYTES CONFIRM_FILES CONFIRM_BYTES CONFIRM_WEIGHT PARAM_RATE PARAM_LATENCY
---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------- ----------- ---------- ---------- ------------- ------------- -------------- ---------- -------------
1307536800        300       1261          9          1        674 1.9428E+12         17 6.2126E+10                               444  1.3391E+12        213 5.4159E+11           674    1.9428E+12              42622776.5             0
1307536800        300       1261          9          3       2235 8.2929E+12        108 3.8492E+11                              1340  4.9314E+12        787 2.9765E+12          2241    8.3173E+12              42622776.5             0
1307536800        300       1261          9          5          1 4056075153                                                       1  4056075153                                   1    4056075153              42622776.5             0
-verbatim-

This is transient, and the calculated latency is usually corrected on the next PerfMonitor cycle, but even a transient issue has a negative consequence on the FileRouter: if the FileRouter agent finds a link with latency=0, it may incorrectly extend all transfer paths that are about to expire on the link instead of rerouting the transfers.

Possible reason for the bug: the &quot;pend_bytes&quot; value used by PerfMonitor in the latency calculation is taken from the latest timebin of (t_history_link_events full join t_history_link_stats). The t_history_link_stats table which contains the pend_bytes column is updated by PerfMonitor itself (cycle-time ~ 6 mins) while t_history_link_events is updated much more frequently by FilePump (cycle-time ~ 2 mins). Therefore, FilePump can insert new rows before PerfMonitor has the chance to complete the current cycle. For these rows, there would not be any corresponding entry in t_history_link_stats, so the pend_bytes column would be NULL in the full join.

Possible solution: only look at rows inserted before the current timebin when retrieving stats to calculate the latency?

Nicolo'

**Comment by nikmagini** [comment]
Fix released in PhEDEx 4.1.8 and deployed to production around Thu Jun  9 13:50:00 UTC 2016 - I haven't seen rows with 0 latency and non-zero pend_bytes since then, closing issue finally
