### ISSUE TITLE
File path still valid 5 days after source replica deletion

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/PHEDEX#792]
Original Savannah ticket 85191 reported by None on Thu Aug  4 10:46:54 2011.

Hi,

from the following Savannah ticket:

https://savannah.cern.ch/support/?122604

5 files were routed on the T2_CN_Beijing--&gt;T2_US_Purdue link.

On July 30th, Purdue deleted the source files, but on August 4th the paths were still valid on the link, so FileIssue could not recreate the transfer tasks and the transfer was stuck.
Suspending/unsuspending the subscription cleared the paths.

To be understood how this is possible: perhaps the tasks were unduly extended, or the paths were revalidated by the FileRouter slow flush.

N.

**Comment by nikmagini** [comment]
Fix released with PhEDEx 4.1.8 and deployed in production on 2016-06-09
Now the FileRouter will let paths with deleted file replica expire, so they will be cleaned up from TMDB after 7-10 hours (expiration time).
Checking in the DB on 2016-06-10, there are no old such paths in TMDB anymore, only recent ones which are going to expire soon. Closing!
