### ISSUE TITLE
NOCACHE parameter and -nocache option in dcache Namespace

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/PHEDEX#821]
Original Savannah ticket 88478 reported by ratnik on Thu Nov  3 13:30:14 2011.

As discussed in bug #88472, there is an inconsistency between the 
NOCACHE parameter, which requires an argument, and the --nocache option described in help, which does not require an argument. 

Besides that, the --nocache option is not recognized by the agent: probably not propagated correctly through the Namespace.
To be investigated.

**Comment by nikmagini** [comment]
Option --nocache added to the BDV agent in 4.2.0 - only 5 years later ;)
