### ISSUE TITLE
Move subscription is not working properly

### ISSUE THREAD

**Issue by merictaze** [dmwm/PHEDEX#946]
Hi Tony,

I tested move subscription on Dev instance after updating it to 4.1.3, but it did not run as expected.

I created a move request for the data[1] to T1_UK_RAL_MSS. I was expecting that it will be removed from all nodes except MSSes. However, it was removed from only T2_CH_CERN and T3_GR_Demokritos [2]. 

Cheers,
Meric

[1] https://cmsweb.cern.ch/phedex/datasvc/xml/dev/blockreplicas?block=/Dev/LoadTest/Alpha%231

[2] https://cmsweb.cern.ch/phedex/test/Activity::Deletions?reqfilter=&node=.*&state=any&blockfilter=%2FDev%2FLoadTest%2FAlpha.*&.submit=Update#

**Comment by merictaze** [comment]
Hi Tony,

After deploying PhEDEx 4.1.4 in prod, I found a new bug
Issue is the following:

- WMAgent injected some blocks to T1_US_FNAL_Disk on Feb 3 [1]
- Move request to T0 was created on Feb4 by WMAgent, approved on Feb5 [2]
- PhEDEx cleaned FNAL_Disk from these blocks.
- WMAgent continued to inject some more blocks to the dataset at FNAL_Disk. (It doesn't wait WF to finish to submit move request)
- The ones injected after Feb5 are still registered to FNAL_Disk [3]

I think the scenario would be the same even if FNAL_Disk was subscribed to the sample, and approve move request as a source site to be cleaned up. Blocks&Files which are injected after the source deletion approved will continue to stay on disk.

Cheers,
Meric

[1] dataset time_create
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/data?dataset=/QCD_Pt-15to3000_Tune4C_Flat_14TeV_pythia8/GEM2019Upg14DR-Phase1age1kJan23_PU140BX25_PH1_1K_FB_V3-v1/GEN-SIM-RECO

[2] https://cmsweb.cern.ch/phedex/prod/Request::View?request=432853

[3] https://cmsweb.cern.ch/phedex/datasvc/xml/prod/blockreplicas?dataset=/QCD_Pt-15to3000_Tune4C_Flat_14TeV_pythia8/GEM2019Upg14DR-Phase1age1kJan23_PU140BX25_PH1_1K_FB_V3-v1/GEN-SIM-RECO

**Comment by nikmagini** [comment]
Hi all,

https://github.com/dmwm/PHEDEX/commit/ee621088f3586f2a8e895165c2a0b39d70bfb6d6

this should fix the edge-case reported by Meric, more detailed explanation here

https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/2001/3/2/1/1/1/1/1.html

**Comment by nikmagini** [comment]
Hi,

4.1.5pre3 built with this fix, in testing.

N

**Comment by nikmagini** [comment]
Fix deployed in production in Sep 2015 with PhEDEx 4.1.5  - closing.

Nicolò
