### ISSUE TITLE
cannot request move: moves to non-T0, non-T1 destinations are not allowed

### ISSUE THREAD

**Issue by DAMason** [dmwm/PHEDEX#978]
I'm trying to do a move request via the web interface to T1_US_FNAL_Disk and am getting the error:

cannot request move: moves to non-T0, non-T1 destinations are not allowed\n

Pretty sure FNAL is a T1 however ;)

**Comment by TonyWildish** [comment]
Hi Dave,

the code harks back to the days before _Disk nodes, so only _MSS nodes were considered. The fix is in testing, but hasn't made it to cmsweb yet. You can try it yourself if you use phedex-web-dev.cern.ch instead of cmsweb.cern.ch (you'll need a tunnel). Let me know if it works.

Cheers,
Tony.

**Comment by DAMason** [comment]
Hi Tony,

After fumbling around with the tunnel a bit it looks like I did make a successful request:

Datasvc call returned:
{request_timestamp => 1421903827.55588, instance => prod, request_created => [{id => 432185}], request_url => http://phedex-web-dev.cern.ch:7001/phedex/datasvc/json/prod/subscribe, request_version => 2.3.19pre3, request_call => subscribe, call_time => 0.44547, request_date => 2015-01-22 05:17:07 UTC}

Then hopping over to the regular production interface I see the request and then approved it.  Should I have seen pending deletion requests on the sites this dataset was sourced at?

Thanks — will watch to see if the transfer does as expected, but so far so good!

—Dave

**Comment by TonyWildish** [comment]
Hi Dave,

you should see the deletion requests, I think, but mixing phedex-web-dev and cmsweb might confuse things. If you don't see them please just make them by hand, Meric is testing the pre-release code fully and can make any bug reports for problems that arise.

**Comment by nikmagini** [comment]
Deployed to cmsweb in April 8th release, closing.
