### ISSUE TITLE
PhEDEx 4.1.3 is missing from the release TWiki page

### ISSUE THREAD

**Issue by t-linden** [dmwm/PHEDEX#992]
PhEDEx 4.1.3 is not listed at the release TWiki page at https://twiki.cern.ch/twiki/bin/view/CMS/PhedexReleases

**Comment by nikmagini** [comment]
Dear Tomas,

that for the notice. Unfortunately the PhEDEx integration team which used to take care of this does not exist anymore, so we cannot guarantee a timely update of the release notes. Anyway I have now added them, closing.

Best Regards,
Nicolo'
